In [1]:
import pImpactR as impact
import numpy as np
import matplotlib.pyplot as plt
MLI = impact.MLI
mli = impact.data.dictClass()
pip = impact.data.dictClass()

In [2]:
# mass = impact.util.Me
# q = 1
# g0 = 133.537
# b0 = np.sqrt((g0+1.0)*(g0-1.0))/g0
# bg0 = g0*b0
# brho = bg0*mass/impact.util.cLight
# energy = mass*g0

mass = 0.000511005*1.0e9
energy = 1.0e8 + mass
q = -1.0

In [3]:
mli.beam = MLI.getElem.beam(mass=mass*1.0e-9,charge=q,ekinetic=(energy-mass)*1.0e-9)
mli.elemList = MLI.getElem.elemList(mli.beam)
# mli.elem= MLI.getElem.drift(name='testelem',l=0.4)
# mli.elem= MLI.getElem.quadrupole(name='testelem',l=1.0e-4,k1=100.0)
mli.elem= MLI.getElem.thlm(name='testelem',k1l=20)
# mli.elem= MLI.getElem.sbend(name='testelem',l=0.8092963858,angle=1.047197551,fint=0.5,hgap=0.5*0.058)
mli.elemList.append(mli.elem)
mli.ptm = MLI.getElem.ptm()
mli.elemList.append(mli.ptm)
mli.lineList = [MLI.getElem.line(elemList=[mli.elem])]
mli.labor = [mli.lineList[0].name,mli.ptm.name]
MLI.writeInputfile(mli.elemList,mli.lineList,mli.labor)
MLI.run()
M,G=MLI.readTransferMap()
M.to_csv('M.mli.csv',header=False,index=False)
M

      1    2     3    4    5    6
1   1.0  0.0   0.0  0.0  0.0  0.0
2 -20.0  1.0   0.0  0.0  0.0  0.0
3   0.0  0.0   1.0  0.0  0.0  0.0
4   0.0  0.0  20.0  1.0  0.0  0.0
5   0.0  0.0   0.0  0.0  1.0  0.0
6   0.0  0.0   0.0  0.0  0.0  1.0

In [4]:
!cat mli.in
!rm mli.out

#menu

beam: beam, ekinetic=0.1, mass=0.0005110050000000001, charge=-1.0
units: units, type=static
setdefaults: globaldefaults, lfrngsbend=1, tfrngsbend=1, lfrngquad=0, tfrngquad=0, driftexact=0
testelem: thlm, k1l=20
ptm: ptm, matrix=3, poly=3

lattice, line=( testelem )
#labor
lattice
ptm

In [5]:
pip.beam = impact.mli2impact.beam(mli.elemList)
pip.lattice = impact.mli2impact.lattice(mli.elemList,mli.lineList[0])
M=impact.getTransferMap(pip.beam,pip.lattice,epsilon=[1.0e-9]*6)
M.to_csv('M.impact.csv',header=False,index=False)
M

      0    1     2    3    4    5
0   1.0  0.0   0.0  0.0  0.0  0.0
1 -20.0  1.0   0.0  0.0  0.0  0.0
2   0.0  0.0   1.0  0.0  0.0  0.0
3   0.0  0.0  20.0  1.0  0.0  0.0
4   0.0  0.0   0.0  0.0  1.0  0.0
5   0.0  0.0   0.0  0.0  0.0  1.0

In [6]:
!cat test.in
!rm fort.*

!================= Beam & Control Parameters =================
1 1
6 6 1 0 1
32 32 32 1 0.014 0.014 0.1
23 0 0 1
6
0.0
-1.95692801440299e-06
0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 100000000.0 511005.0000000001 -1.0 30000000.0 0.0
!========================== Lattice ==========================
0.0 0 0 -16 0.0 1 /
0.0 0 0 5 0.0 0.0 20 0.0 0.0 0.0 0.0 /
0.0 0 5926 -2 2 1 1 /

In [7]:
elemList,lattice=impact.impact2mli(pip.beam,pip.lattice)

In [8]:
elemList.append(mli.ptm)
mli.labor[0]=lattice.name
MLI.writeInputfile(elemList,[lattice],mli.labor)
MLI.run()
M,G=MLI.readTransferMap()
M

      1    2     3    4    5    6
1   1.0  0.0   0.0  0.0  0.0  0.0
2 -20.0  1.0   0.0  0.0  0.0  0.0
3   0.0  0.0   1.0  0.0  0.0  0.0
4   0.0  0.0  20.0  1.0  0.0  0.0
5   0.0  0.0   0.0  0.0  1.0  0.0
6   0.0  0.0   0.0  0.0  0.0  1.0

In [9]:
!cat mli.in
!rm mli.out

#menu

beam: beam, ekinetic=0.1, mass=0.0005110050000000001, charge=-1.0
units: units, type=static
setdefaults: globaldefaults, lfrngsbend=1, tfrngsbend=1, lfrngquad=0, tfrngquad=0, driftexact=1
thlm1: thlm, k1l=20, k2l=0.0, k3l=0.0
ptm: ptm, matrix=3, poly=3

impactLattice, line=( thlm1 )
#labor
impactLattice
ptm